<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Simple HTML with PHP</title>
</head>
<body>
    <header>
        <h1>Simple HTML with PHP</h1>
    </header>
    <section>
        <h2>Random Number Generated by PHP</h2>
        <?php
            // Generate a random number between 1 and 100
            $random_number = rand(1, 100);
            echo "<p>The random number is: $random_number</p>";
        ?>
    </section>
</body>
</html>
